### ISSUE TITLE
Are there any plans to implement a micro-xmr-signer

### ISSUE THREAD

**Issue by vae520283995** [paulmillr/micro-sol-signer#1]
Sorry, I shouldn't have said that here.
Since Monero transactions involve Bulletproofs, Ring Confidential Transactions and ring signatures, etc., there is currently no simple library to support transfers, I found a library with only one file https://github.com/CoinSpace/cs-monero-wallet, but it still contains a lot of cpp code dependencies https://github.com/mymonero/monero-core-custom, Do you plan to study monero ring signatures?

**Comment by paulmillr** [comment]
XMR is great, but no immediate plans. The key gen seems simple enough for noble/ed and noble/hashes. Just make sure you work in LE (little-endian) encoding and not BE.

**Comment by vae520283995** [comment]
> XMR is great, but no immediate plans. The key gen seems simple enough for noble/ed and noble/hashes. Just make sure you work in LE (little-endian) encoding and not BE.

okay, thank you

**Comment by mahnunchik** [comment]
@paulmillr I've the same question: any plans to implement Monero library?

* Address derivation, key derivation, and Ring CT things are implemented here https://github.com/CoinSpace/monerolib
* Not implemented yet Bulletproofs and Bulletproofs+ https://github.com/monero-project/monero/tree/8349cfe4a63cfc63d50ce3818886b67a05e240a4/src/ringct

So it should be a good challenge to bring Monero to JS ecosystem.

**Comment by paulmillr** [comment]
@mahnunchik still overwhelmed with other tasks. No plans for now, but it should be really simple if someone could get onto it.

The first step  here is address generation. Fairly straightforward.

**Comment by vae520283995** [comment]
@mahnunchik @paulmillr  Can we first create a micro-xmr-signer repository and then generate the Standard address and Subaddress through cure-base, noble-cures, and noble-hashes?

**Comment by paulmillr** [comment]
@vae520283995 I don't trademark `micro` - anyone's free to create the library!

**Comment by vae520283995** [comment]
> @vae520283995 I don't trademark `micro` - anyone's free to create the library!

Sorry, my native language is not English, so there is ambiguity. I hope you create a micro-xmr-signer, and then @mahnunchik  or other developers will add some functions, and if you have time, you can write code again, or refactor Code, because there is no simple library for monero in github, I hope this can be the first

**Comment by paulmillr** [comment]
@vae520283995 my point is that @mahnunchik can create xmr-signer repository and people can contribute to it.

**Comment by mahnunchik** [comment]
Library was created two years ago: https://github.com/CoinSpace/monerolib

@vae520283995 address derivation can be found here: https://github.com/CoinSpace/monerolib/blob/23fda29ebe7bbaae024ba6f0913f6070c813e74d/lib/address.js

Library can be easily migrated to noble-cures, noble-hashes etc, but my attempt to implement Bulletproofs and Bulletproofs+ in JS was unsuccessful. Bulletproofs is required to complete transaction signing.

**Comment by vae520283995** [comment]
> Library can be easily migrated to noble-cures, noble-hashes etc, but my attempt to implement Bulletproofs and Bulletproofs+ in JS was unsuccessful. Bulletproofs is required to complete transaction signing.

Sorry I don't know anything about Bulletproofs
