### ISSUE TITLE
Add formats of private key

### ISSUE THREAD

**Issue by mahnunchik** [paulmillr/micro-sol-signer#6]
I think it might be helpful if the library can encode the private key in the following formats:

* `array` - string representation of uint8 array `[1, 2, 3...]`, used in https://solflare.com/ wallet
* `hex` - used in https://guarda.co/app
* `base58` - current one, the most logical in my opinion

Method signature can be like this:
```js
formatPrivate(privateKey, format='base58') {}
```

**Comment by paulmillr** [comment]
makes sense
